name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        pip install pylint
        pip install docopt
        pip install bs4
        pip install mock
        pip install html-testRunner
        pip install xmlrunner
        pip install wheel
        pip install twine
    - name: Analysing the code with pylint
      run: |
        pylint tests/
        pylint pystandalonehtml/
    - name: Testing and Reporting with tox
      run: |
        tox --result-json reports/report.json
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN_TEST }}
        repository_url: https://test.pypi.org/legacy/