name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          pip install pylint
          pip install docopt
          pip install bs4
      - name: Analysing the code with pylint
        run: |
          echo "[1 ]Running lint process in pystandalonehtml/"
          pylint pystandalonehtml/
      - name: Second Testing
        run: |
          find . -name 'pystandalonehtml/*.py' -exec pylint {} \;
      - name: Test
        run: |
          echo "[R] Running unit test"
      - name: Report
        run: |
          echo "[T] Generating reports"
      - name: Deploy
        run: echo "[D] Deploying to pypi"
